### ISSUE TITLE
[DOCS] Contributing Guide

### ISSUE THREAD

**Issue by Arnav-2004** [dhzdhd/Obsidian#17]
Adding a contributing guide would help people to better understand how to contribute to this repository properly.

**Comment by dhzdhd** [comment]
I agree, do you want to work on it?

**Comment by Arnav-2004** [comment]
Sure!

**Comment by dhzdhd** [comment]
Alright

**Comment by Arnav-2004** [comment]
Would you prefer a new file `CONTRIBUTING.md` or just an addition to `README.md`
